詳細画面 学童対応
codeforchiba/pamasapo pull request #169
Opened 2020-09-23 22:06 UTC by snakamu

2020-09-24 14:12 UTC, misopeso requested changes
ちょろっと手直ししていただけると！

2020-09-24 14:12 UTC, misopeso commented on components/nurseries/Detail.vue
> +      const facility = this.item.nursery ? this.item.nursery.facility : "";
nursery の下に facility がないことはないはずなので、ここの考慮は不要かと思います。

2020-09-24 14:12 UTC, misopeso commented on components/nurseries/Detail.vue
>    </v-list>
備考が重複しちゃうので、備考のデータを computed で算出する形にしてはいかがでしょうか？

```
remarks() {
  if (item.nursery) {
    return item.nursery.facility.remarks
  } else if (item.afterSchool) {
    return item.afterSchool.facility.remarks
  } else {
    return null
  }
}
```

のような感じです(サンプルで適当なので、もっときれいにやっていただけると :bow: )

2020-09-24 14:12 UTC, misopeso commented on components/nurseries/Service.vue
>      </v-list-item>
項目単位ではなく `<template>` でくくって、一気に `v-if` のほうがよいかと思いますー

2020-09-24 14:12 UTC, misopeso commented on components/nurseries/Service.vue
> +    <v-list-item v-if="item.nursery && item.nursery.service.remarks">
ここも `service` がないことはないはずなので、気にしてくてよいかと思います。

2020-09-24 14:12 UTC, misopeso commented on components/nurseries/Service.vue
> +        <v-list-item-title>{{ item.afterSchool.service.remarks }}</v-list-item-title>
備考のところは、上記と同じような感じにしていただけるとー

2020-09-24 14:12 UTC, misopeso commented on components/nurseries/Status.vue
> +  <v-list v-if="item.nursery" dense>
ここでチェックするなら、もっと上位でできませんか？ この親のコンポーネントのところとか。

2020-09-24 14:12 UTC, misopeso commented on components/nurseries/Summary.vue
> +      }
フォーマッタが整備できていないですが、こんな感じがよいです(ちなみに、セミコロンなくてもよいです)。

```suggestion
      if (this.item.nursery) {
        openingTime = this.item.nursery.facility.openingTime;
        closingTime = this.item.nursery.facility.closingTime;
      }
```

2020-09-25 14:00 UTC, misopeso submitted a review, later dismissed
LGTM!

2020-09-25 14:03 UTC, misopeso commented
以下の URL でみると、備考欄が 2連続ででてます。

https://deploy-preview-169--pamasapo.netlify.app/nurseries/102-sampledata

2020-09-26 01:14 UTC, k-hata approved these changes
設備の備考欄とサービスの備考欄なので見出しの付け方の工夫で対応かな。
値なしの場合の表示方法は私がタスク持っているので、そちらで合わせて修正するとして一旦Developにマージします。

2020-09-26 01:14 UTC, merged