詳細画面で備考欄が複数見えるの対応
codeforchiba/pamasapo pull request #173
Opened 2020-09-27 16:30 UTC by k-hata

**Trello**
https://trello.com/c/qrAvXs5h/139-

**修正内容**
次の3つの備考欄の内容を1か所に統合
・施設基本情報備考
・保育施設属性備考/学童施設属性備考
・保育サービス備考/学童サービス備考

レイアウトとして施設基本情報のあった地図の上に表示

**スクリーンショット**
![image](https://user-images.githubusercontent.com/3695706/94370273-02abcd80-012a-11eb-8054-508f25d6fd96.png)

2020-09-27 16:34 UTC, k-hata commented
![](https://github.trello.services/images/mini-trello-icon.png) [学童の詳細画面で備考欄が2つ続いて見える](https://trello.com/c/qrAvXs5h/139-%E5%AD%A6%E7%AB%A5%E3%81%AE%E8%A9%B3%E7%B4%B0%E7%94%BB%E9%9D%A2%E3%81%A7%E5%82%99%E8%80%83%E6%AC%84%E3%81%8C2%E3%81%A4%E7%B6%9A%E3%81%84%E3%81%A6%E8%A6%8B%E3%81%88%E3%82%8B)

2020-09-29 02:22 UTC, misopeso commented
3つあったときって、どういう表示になります？

2020-10-01 10:16 UTC, k-hata commented
全部連結されます…せめて改行はいりますね。

2020-10-04 05:37 UTC, k-hata commented
3つの備考欄について、改行をいれて一カ所にまとめて表示するよう変更(図は保育園で表示した場合)。
![image](https://user-images.githubusercontent.com/3695706/95007831-0f12b780-064f-11eb-98c8-c5079c6826e2.png)

2020-10-04 05:43 UTC, misopeso requested changes

2020-10-04 05:43 UTC, misopeso commented on components/nurseries/Summary.vue
> +      return remarks;
ここは、そのまま返しちゃえばいいのでは？

2020-10-04 05:43 UTC, misopeso commented on components/nurseries/Summary.vue
> +        <v-list-item-title>{{ serviceRemarks }}</v-list-item-title>
title が 3つあるのも気持ち悪いので、 `<v-list-item-title>` は 1つにして `<p>` で 1つ1つを囲めばいいと思います。

2020-10-04 05:52 UTC, k-hata commented on components/nurseries/Summary.vue
> +      return remarks;
あ、確かに。

2020-10-04 05:55 UTC, k-hata commented on components/nurseries/Summary.vue
> +        <v-list-item-title>{{ serviceRemarks }}</v-list-item-title>
<p>で囲むとこんな感じで隙間があきます。
<br>だと前のように隙間なくなりますが、どっち良いとかありますか。
![image](https://user-images.githubusercontent.com/3695706/95008086-86e1e180-0651-11eb-9906-7dd23c68bd51.png)

2020-10-04 08:49 UTC, k-hata commented
値がある備考欄のみ、改行して表示するように修正。
![image](https://user-images.githubusercontent.com/3695706/95011183-d92efc80-0669-11eb-8d82-9bf624dd9fdd.png)

2020-10-04 12:40 UTC, misopeso approved these changes
スタイル調整は後ってことで LGTM!

2020-10-04 12:40 UTC, merged